import {BookResponse} from "../../../services/models/book-response";

export  var books: BookResponse[] = [
  {
    archived: false,
    authorName: "J.K. Rowling",
    cover: ["https://m.media-amazon.com/images/I/81q77Q39nEL._SL1500_.jpg"],
    id: 1,
    isbn: "9780747532743",
    owner: "John Doe",
    rate: 2.4,
    shareable: true,
    synopsis: "Harry Potter discovers he's a wizard and attends Hogwarts.",
    title: "Harry Potter and the Philosopher's Stone",
  },
  {
    archived: false,
    authorName: "J.R.R. Tolkien",
    cover: ["https://m.media-amazon.com/images/I/71ROByrJziL._SL1000_.jpg"],
    id: 2,
    isbn: "9780261103573",
    owner: "Jane Smith",
    rate: 4.9,
    shareable: true,
    synopsis: "A hobbit embarks on a journey to destroy a powerful ring.",
    title: "The Lord of the Rings",
  },
  {
    archived: true,
    authorName: "George Orwell",
    cover: ["https://m.media-amazon.com/images/I/71yFJ1MZLZL._SL1500_.jpg"],
    id: 3,
    isbn: "9780451524935",
    owner: "Library Archive",
    rate: 4.7,
    shareable: false,
    synopsis: "A dystopian future under constant surveillance.",
    title: "1984",
  },
  {
    archived: false,
    authorName: "Harper Lee",
    cover: ["https://m.media-amazon.com/images/I/51lVvSDLQJL._SL1052_.jpg"],
    id: 4,
    isbn: "9780061120084",
    owner: "Alice Brown",
    rate: 4.6,
    shareable: true,
    synopsis: "A young girl confronts racial injustice in the Deep South.",
    title: "To Kill a Mockingbird",
  },
  {
    archived: false,
    authorName: "F. Scott Fitzgerald",
    cover: ["https://m.media-amazon.com/images/I/7150R+R19WL._SL1499_.jpg"],
    id: 5,
    isbn: "9780743273565",
    owner: "Tom Wilson",
    rate: 4.3,
    shareable: true,
    synopsis: "A mysterious millionaire and his obsession with Daisy.",
    title: "The Great Gatsby",
  },
  {
    archived: true,
    authorName: "Mary Shelley",
    cover: ["https://m.media-amazon.com/images/I/61b1z9pzZzL._SL1499_.jpg"],
    id: 6,
    isbn: "9780486282114",
    owner: "Museum",
    rate: 4.5,
    shareable: false,
    synopsis: "A scientist creates a living being with unintended consequences.",
    title: "Frankenstein",
  },
  {
    archived: false,
    authorName: "Leo Tolstoy",
    cover: ["https://m.media-amazon.com/images/I/61UyS0rJc2L._SL1200_.jpg"],
    id: 7,
    isbn: "9781400079988",
    owner: "Olivia Stone",
    rate: 4.8,
    shareable: true,
    synopsis: "A sweeping tale of love, war, and history in Russia.",
    title: "War and Peace",
  },
  {
    archived: false,
    authorName: "Gabriel García Márquez",
    cover: ["https://m.media-amazon.com/images/I/71WQQjgEhQL._SL1500_.jpg"],
    id: 8,
    isbn: "9780060883287",
    owner: "Carlos Hernandez",
    rate: 4.7,
    shareable: true,
    synopsis: "A multi-generational story of the Buendía family.",
    title: "One Hundred Years of Solitude",
  },
  {
    archived: false,
    authorName: "Jane Austen",
    cover: ["https://m.media-amazon.com/images/I/619cqIHeS6L._SL1500_.jpg"],
    id: 9,
    isbn: "9780141439518",
    owner: "Emma Green",
    rate: 4.6,
    shareable: true,
    synopsis: "A romantic novel exploring themes of manners and marriage.",
    title: "Pride and Prejudice",
  },
  {
    archived: false,
    authorName: "Mark Twain",
    cover: ["https://m.media-amazon.com/images/I/61Vo8m1E04L._SL1499_.jpg"],
    id: 10,
    isbn: "9780486280615",
    owner: "Samuel Clemens",
    rate: 4.4,
    shareable: true,
    synopsis: "The adventures of a boy and a runaway slave on the Mississippi River.",
    title: "The Adventures of Huckleberry Finn",
  },
];
